server:
 port: 8080
 servlet:
    context-path: /
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            wiretap: true
          discovery:
            locator:
              enabled: true
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          routes:
            - id: ms-service1
              uri: lb://SERVICE1
              predicates:
                - Path=/api/service1/**
            - id: ms-service2
              uri: lb://SERVICE2
              predicates:
                - Path=/api/service2/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
  server:
    enable-self-preservation: false