server:
 port: 8080
 servlet:
    context-path: /
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: ms-service1
          uri: lb://SERVICE1
          predicates:
            - Path=/service1/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
  server:
    enable-self-preservation: false