server:
 port: 8080
 servlet:
    context-path: /
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      discovery:
       locator:
        lower-case-service-id: true
        enabled: true
      routes:
        - id: service1
          uri: lb://service1
          predicates:
            - Path=/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
  server:
    enable-self-preservation: false